# Generated by Django 4.0.4 on 2022-04-23 01:30

from django.db import migrations, models
import vrcode.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=70, unique=True)),
                ('name', models.CharField(default='', max_length=300)),
                ('img', models.ImageField(blank=True, null=True, upload_to=vrcode.models.upload_img_path)),
            ],
        ),
    ]
